/**
 * Created by Lee on 2015/11/26.
 */
var EnemyAI = {
	proto: {
		reflectionTime: null,
		instinctTemplate: {
			easyAttackBegin: null,
			hardAttackBegin: null,
			moveAsideBegin: null,
			moveForwardBegin: null,
			moveBackwardBegin: null,
			operateAdjust: null,
			adjustToFace: null,
			defenceBegin: null,
			blockBegin: null,
			operateEnergyBegin: null
		},
		instinct: {},
		energyEffect: {
			easyAttackBegin: null,
			hardAttackBegin: null,
			moveAsideBegin: null,
			moveForwardBegin: null,
			moveBackwardBegin: null,
			operateAdjust: null,
			adjustToFace: null,
			defenceBegin: null,
			blockBegin: null,
			operateEnergyBegin: null
		},
		mightMeEffect: {
			easyAttackBegin: null,
			hardAttackBegin: null,
			moveAsideBegin: null,
			moveForwardBegin: null,
			moveBackwardBegin: null,
			operateAdjust: null,
			adjustToFace: null,
			defenceBegin: null,
			blockBegin: null,
			operateEnergyBegin: null
		},
		mightEnemyEffect: {
			easyAttackBegin: null,
			hardAttackBegin: null,
			moveAsideBegin: null,
			moveForwardBegin: null,
			moveBackwardBegin: null,
			operateAdjust: null,
			adjustToFace: null,
			defenceBegin: null,
			blockBegin: null,
			operateEnergyBegin: null
		},
		weakMeEffect: {
			easyAttackBegin: null,
			hardAttackBegin: null,
			moveAsideBegin: null,
			moveForwardBegin: null,
			moveBackwardBegin: null,
			operateAdjust: null,
			adjustToFace: null,
			defenceBegin: null,
			blockBegin: null,
			operateEnergyBegin: null
		},
		weakEnemyEffect: {
			easyAttackBegin: null,
			hardAttackBegin: null,
			moveAsideBegin: null,
			moveForwardBegin: null,
			moveBackwardBegin: null,
			operateAdjust: null,
			adjustToFace: null,
			defenceBegin: null,
			blockBegin: null,
			operateEnergyBegin: null
		},
		acting: {
			easyAttackBegin: false,
			hardAttackBegin: false,
			moveAsideBegin: false,
			moveForwardBegin: false,
			moveBackwardBegin: false,
			operateAdjust: false,
			adjustToFace: false,
			defenceBegin: false,
			blockBegin: false,
			operateEnergyBegin: false
		},
		operationPossibility: {
			upInstinct: null,
			downInstinct: null,
		},
		maxPossibility: {
			upInstinct: null,
			downInstinct: null,
		},
		actionTime: 0,
	},
	instance: {
		enemy: {
			reflectionTime: [200, 500],

			instinctTemplate_easyAttackBegin: 20,
			instinctTemplate_hardAttackBegin: 20,
			instinctTemplate_moveAsideBegin: 20,
			instinctTemplate_moveForwardBegin: 20,
			instinctTemplate_moveBackwardBegin: 20,
			instinctTemplate_operateAdjust: 20,
			instinctTemplate_adjustToFace: 20,
			instinctTemplate_defenceBegin: 20,
			instinctTemplate_blockBegin: 20,
			instinctTemplate_operateEnergyBegin: 20,

			energyEffect_easyAttackBegin: 20,
			energyEffect_hardAttackBegin: 20,
			energyEffect_moveAsideBegin: 20,
			energyEffect_moveForwardBegin: 20,
			energyEffect_moveBackwardBegin: 20,
			energyEffect_operateAdjust: 20,
			energyEffect_adjustToFace: 20,
			energyEffect_defenceBegin: 20,
			energyEffect_blockBegin: 20,
			energyEffect_operateEnergyBegin: 20,

			mightMeEffect_easyAttackBegin: 20,
			mightMeEffect_hardAttackBegin: 20,
			mightMeEffect_moveAsideBegin: 20,
			mightMeEffect_moveForwardBegin: 20,
			mightMeEffect_moveBackwardBegin: 20,
			mightMeEffect_operateAdjust: 20,
			mightMeEffect_adjustToFace: 20,
			mightMeEffect_defenceBegin: 20,
			mightMeEffect_blockBegin: 20,
			mightMeEffect_operateEnergyBegin: 20,

			mightEnemyEffect_easyAttackBegin: 20,
			mightEnemyEffect_hardAttackBegin: 20,
			mightEnemyEffect_moveAsideBegin: 20,
			mightEnemyEffect_moveForwardBegin: 20,
			mightEnemyEffect_moveBackwardBegin: 20,
			mightEnemyEffect_operateAdjust: 20,
			mightEnemyEffect_adjustToFace: 20,
			mightEnemyEffect_defenceBegin: 20,
			mightEnemyEffect_blockBegin: 20,
			mightEnemyEffect_operateEnergyBegin: 20,

			weakMeEffect_easyAttackBegin: 20,
			weakMeEffect_hardAttackBegin: 20,
			weakMeEffect_moveAsideBegin: 20,
			weakMeEffect_moveForwardBegin: 20,
			weakMeEffect_moveBackwardBegin: 20,
			weakMeEffect_operateAdjust: 20,
			weakMeEffect_adjustToFace: 20,
			weakMeEffect_defenceBegin: 20,
			weakMeEffect_blockBegin: 20,
			weakMeEffect_operateEnergyBegin: 20,

			weakEnemyEffect_easyAttackBegin: 20,
			weakEnemyEffect_hardAttackBegin: 20,
			weakEnemyEffect_moveAsideBegin: 20,
			weakEnemyEffect_moveForwardBegin: 20,
			weakEnemyEffect_moveBackwardBegin: 20,
			weakEnemyEffect_operateAdjust: 20,
			weakEnemyEffect_adjustToFace: 20,
			weakEnemyEffect_defenceBegin: 20,
			weakEnemyEffect_blockBegin: 20,
			weakEnemyEffect_operateEnergyBegin: 20,

			acting_easyAttackBegin: 20,
			acting_hardAttackBegin: 20,
			acting_moveAsideBegin: 20,
			acting_moveForwardBegin: 20,
			acting_moveBackwardBegin: 20,
			acting_operateAdjust: 20,
			acting_adjustToFace: 20,
			acting_defenceBegin: 20,
			acting_blockBegin: 20,
			acting_operateEnergyBegin: 20,

			operationPossibility_upInstinct: 20,
			operationPossibility_downInstinct: 20,

			maxPossibility_upInstinct: 20,
			maxPossibility_downInstinct: 20,
		},
	}
};
