var res = {
    Bar0 : "res/0Bar.png",
    BarShow0 : "res/0BarShow.png",
    Dot0 : "res/0Dot.png",
    Rec0 : "res/0Rec.png",
    Bar3 : "res/3Bar.png",
    BarShow3 : "res/3BarShow.png",
    Dot3 : "res/3Dot.png",
    Rec3 : "res/3Rec.png",
    Bar4 : "res/4Bar.png",
    BarShow4 : "res/4BarShow.png",
    Dot4 : "res/4Dot.png",
    Rec4 : "res/4Rec.png",
    Bar1 : "res/1Bar.png",
    BarShow1 : "res/1BarShow.png",
    Dot1 : "res/1Dot.png",
    Rec1 : "res/1Rec.png",
    Bar2 : "res/2Bar.png",
    BarShow2 : "res/2BarShow.png",
    Dot2 : "res/2Dot.png",
    Rec2 : "res/2Rec.png",

    easyAttack : "res/easyAttack.png",
    easyGo : "res/easyGo.png",
    easyNo: "res/easyNo.png",
    hardAttack : "res/hardAttack.png",
    hardGo : "res/hardGo.png",
    hardNo: "res/hardNo.png",
    attack : "res/attack.png",
    noAttack: "res/noAttack.png",
    attackProgress : "res/attackProgress.png",
    defence : "res/defence.png",
    noDefence: "res/noDefence.png",
    block : "res/block.png",
    position : "res/position.png",
    noPosition: "res/noPosition.png",
    face : "res/face.png",
    halfFace : "res/halfFace.png",
    broadsideOnEnemy: "res/broadsideOnEnemy.png",
    enemyBroadsideOnMe: "res/enemyBroadsideOnMe.png",
    enemyFacedToMe: "res/enemyFacedToMe.png",
    noAction : "res/noAction.png",
    noActionGo: "res/noActionGo.png",
    noActionStop: "res/noActionStop.png",
    forward : "res/forward.png",
    backward : "res/backward.png",
    slide: "res/slide.png",

    backGround : "res/backGround.png",
    buttonProgress : "res/buttonProgress.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}