var res = {
    Bar0 : "res/0Bar.png",
    energyBar0: "res/energyBarWhite.png",
    BarShow0 : "res/0BarShow.png",
    Dot0 : "res/0Dot.png",
    Rec0 : "res/0Rec.png",
    Bar3 : "res/3Bar.png",
    BarShow3 : "res/3BarShow.png",
    energyBar3: "res/energyBarRed.png",
    Dot3 : "res/3Dot.png",
    Rec3 : "res/3Rec.png",
    Bar4 : "res/4Bar.png",
    BarShow4 : "res/4BarShow.png",
    energyBar4: "res/energyBarYellow.png",
    Dot4 : "res/4Dot.png",
    Rec4 : "res/4Rec.png",
    Bar1 : "res/1Bar.png",
    BarShow1 : "res/1BarShow.png",
    energyBar1: "res/energyBarBlue.png",
    Dot1 : "res/1Dot.png",
    Rec1 : "res/1Rec.png",
    Bar2 : "res/2Bar.png",
    BarShow2 : "res/2BarShow.png",
    energyBar2: "res/energyBarGreen.png",
    Dot2 : "res/2Dot.png",
    Rec2 : "res/2Rec.png",

    easy0 : "res/easyWhite.png",
    easy1: "res/easyBlue.png",
    easy2: "res/easyGreen.png",
    easy3: "res/easyRed.png",
    easy4: "res/easyYellow.png",
    easyGo : "res/easyGo.png",
    easyNo: "res/easyNo.png",
    hard0 : "res/hardWhite.png",
    hard1: "res/hardBlue.png",
    hard2: "res/hardGreen.png",
    hard3: "res/hardRed.png",
    hard4: "res/hardYellow.png",
    hardGo : "res/hardGo.png",
    hardNo: "res/hardNo.png",
    attack0 : "res/attackWhite.png",
    attack1: "res/attackBlue.png",
    attack2: "res/attackGreen.png",
    attack3: "res/attackRed.png",
    attack4: "res/attackYellow.png",
    noAttack: "res/noAttack.png",
    attackProgress : "res/attackProgress.png",
    defence : "res/defence.png",
    noDefence: "res/noDefence.png",
    block : "res/block.png",
    position : "res/position.png",
    noPosition: "res/noPosition.png",
    face : "res/face.png",
    halfFace : "res/halfFace.png",
    broadsideOnEnemy: "res/broadsideOnEnemy.png",
    enemyBroadsideOnMe: "res/enemyBroadsideOnMe.png",
    enemyFacedToMe: "res/enemyFacedToMe.png",
    noAction : "res/noAction.png",
    noActionGo: "res/noActionGo.png",
    noActionStop: "res/noActionStop.png",
    forward : "res/forward.png",
    backward : "res/backward.png",
    slide: "res/slide.png",
    hitMe: "res/hitBarMe.png",
    hitEnemy: "res/hitBarEnemy.png",
    hitMask: "res/hitMask.png",

    backGround : "res/backGround.png",
    buttonProgress : "res/buttonProgress.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}